Repository DivvyHomes/eslint-config-divvyhomes, pull requests merged in 2020-02, with the labels that each got.

#2 Add new ESLint rule to enforce new with Error and CoreError constructors
  eslint-plugin-divvy-rules/index.js
  index.js
Labels: size/S

#3 Fix/jsx a11y illegal config
  index.js
Labels: size/XS

#4 Add/test
  index.js
  package.json
  test.sh
Labels: size/XS

#5 Fix/a11y
  index.js
  package-lock.json
Labels: Stacked PR 🥞, size/S

#7 Add/test
  index.js
  package-lock.json
Labels: size/S
